version: '3.8'
services:
 
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  # (اختياري) واجهة رسومية لرؤية ما بداخل Redis
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"